package none.twitterapp;

import java.io.IOException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Noahb
 */
public class ApiCallWin extends javax.swing.JFrame {
    private APIAuthorization auth;
    private MakeRequest get;
    private String lastResponse;

    /**
     * Creates new form apiCallWIn
     */
    public ApiCallWin(APIAuthorization auth){
        this.auth = auth;
        get = new MakeRequest();
        initComponents();
        btnRequest.setEnabled(false);
    }
    
    private void winRequest() throws IOException{
        String url = jtfURL.getText();
        String response = "";
        if(chkAuthed.isSelected()){
            if(chkCustomAuth.isSelected()) {
                url += jtfKey.getText();
                url += jtfToken.getText();
                response = get.request(url);
            }
        }
        else {
            response = get.request(url);
        }
        lastResponse = response;
        jtaResponse.setText(lastResponse);
    }
    //https://canvas.endicott.edu/api/v1/users/self
    //2548~dC4Ut73ZZ26vD3zzb1Pf2H0lJoEwRwu65XYysZHywUeni2FAfyVD6Dqh4SssYilc
    private void update_fields(){
        boolean authed = chkAuthed.isSelected();
        boolean custom = chkCustomAuth.isSelected();
        chkCustomAuth.setEnabled(authed);
        jtfKey.setEnabled(authed && custom);
        jtfToken.setEnabled(authed && custom);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtaResponse = new javax.swing.JTextArea();
        jtfURL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRequest = new javax.swing.JButton();
        chkCustomAuth = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfKey = new javax.swing.JTextField();
        chkAuthed = new javax.swing.JCheckBox();
        jtfToken = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtaResponse.setColumns(20);
        jtaResponse.setRows(5);
        jScrollPane1.setViewportView(jtaResponse);

        jtfURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfURLActionPerformed(evt);
            }
        });
        jtfURL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfURLKeyTyped(evt);
            }
        });

        jLabel1.setText("Response");

        jLabel2.setText("URL");

        btnRequest.setText("Request");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        chkCustomAuth.setText("Custom Token");
        chkCustomAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCustomAuthActionPerformed(evt);
            }
        });

        jLabel3.setText("Key:");

        jLabel4.setText("Token:");

        jtfKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfKeyActionPerformed(evt);
            }
        });

        chkAuthed.setText("Authed");
        chkAuthed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAuthedActionPerformed(evt);
            }
        });

        jtfToken.setText("jTextField1");
        jtfToken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTokenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfURL, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                            .addComponent(jtfKey)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chkAuthed)
                                .addGap(18, 18, 18)
                                .addComponent(chkCustomAuth))
                            .addComponent(jtfToken))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jtfURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRequest)
                    .addComponent(chkAuthed)
                    .addComponent(chkCustomAuth))
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        try {
            winRequest();
        }
        catch(IOException e){
            System.out.println("fuck java");
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void jtfURLKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfURLKeyTyped
        btnRequest.setEnabled(true);
    }//GEN-LAST:event_jtfURLKeyTyped

    private void chkCustomAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCustomAuthActionPerformed
        
    }//GEN-LAST:event_chkCustomAuthActionPerformed

    private void jtfURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfURLActionPerformed

    private void chkAuthedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAuthedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAuthedActionPerformed

    private void jtfKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfKeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfKeyActionPerformed

    private void jtfTokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTokenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTokenActionPerformed
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRequest;
    private javax.swing.JCheckBox chkAuthed;
    private javax.swing.JCheckBox chkCustomAuth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaResponse;
    private javax.swing.JTextField jtfKey;
    private javax.swing.JTextField jtfToken;
    private javax.swing.JTextField jtfURL;
    // End of variables declaration//GEN-END:variables
}
